name = "Rudiments"
author = "Eyxiong"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1d8dfae0065aa0b61ba44a00a6dd064e76ddb013d5dd37dee7ae459b98f5e7f"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
