name = "Rudiments"
author = "Eyxiong"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d4616a83e07ed90b7734db66bb6838045e3b8d952e170a49ea29fd79ac815ca"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
