name = "Rudiments"
author = "Eyxiong"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4addd40e508c47097245786038447cb4c3c0b38bb416f3847e908a949669e59"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
