name = "Rudiments"
author = "Eyxiong"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41dab06643ea025d0c3e58e3442937acb90b914a7cd1c58aa4793f29bfec901c"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
