name = "Rudiments"
author = "Eyxiong"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "712d459b0d0a06525fe252d0f723f7fca1816fcdfddc89f2dd20d970cac7de72"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
